all: samToBed viterbi hmcnc

hmmcnc.o: hmmcnc.cpp
	g++ -c -g2 -I $(CONDA_PREFIX)/include $^ -o $@

hmcnc_io.o: hmcnc_io.cpp
	g++ -c -g2 -I $(CONDA_PREFIX)/include $^ -o $@

hmcnc: main.cpp hmmcnc.o hmcnc_io.o
	g++ -g2 -I $(CONDA_PREFIX)/include $^ -o $@ -L $(CONDA_PREFIX)/lib -lhts -lpthread -ffast-math -Wl,-rpath=$(CONDA_PREFIX)/lib

viterbi: viterbi.cpp
	g++ -O2 -I $(CONDA_PREFIX)/include $^ -o $@

samToBed: SamToBed.cpp
	g++ $^ -o $@
